feat: configurable prefix
interledger-deprecated/ilp-plugin-ethereum pull request #7
Opened 2017-07-26 19:19 UTC by michielbdejong

Basically same thing as https://github.com/ripple/ilp-plugin-xrp-escrow/pull/9

Not sure if there is a better way to do `accountToHex`, would it make sense if we created an `ilp-address` library that can parse an ILP address for the ledger part, the account part, etc?

2017-07-27 18:47 UTC, sharafian requested changes

2017-07-27 18:47 UTC, sharafian commented on src/model/ethereum.js
> +const accountToHex = (account) => account.split('.').reverse()[0]
I don't think this is a good way of parsing an ILP address; it doesn't check that it's the correct prefix, nor can it handle a subledger like the original `accountRegex` can. I think a better way would be using the RegExp constructor and passing in the prefix, although the dots and dashes in the prefix would have to be escaped.

2017-07-28 08:15 UTC, michielbdejong commented on src/model/ethereum.js
> +const accountToHex = (account) => account.split('.').reverse()[0]
Yeah, i'm also not sold on the `.split('.').reverse()[0]`, at least it would be cleaner to check if the prefix matches, and we should also probably check if the hex address is uppercase and of the right length:
```js
const accountToHex = (account, ledgerPrefix) => {
  if (!account.startsWith(ledgerPrefix)) {
    throw new Error('account does not start with ledger prefix')
  }
  const match = account.substring(ledgerPrefix.length).match(/^(0x[0-9A-F]{32})$/g)
  if (match === null) {
    throw new Error('account is not a 32-digit upper case hex number')
  }
  return match[0]
}
```
 Also just read that [account identifiers are *one or more* segments that serve as a unique identifier of the account within the ledger](https://github.com/interledger/rfcs/blob/master/0015-ilp-addresses/0015-ilp-addresses.md#account-identifiers) (emphasis mine), but for this plugin, we're defining what ethereum accounts look like, right?

2017-07-28 17:32 UTC, sharafian commented on src/model/ethereum.js
> +const accountToHex = (account) => account.split('.').reverse()[0]
yeah, a plugin could support a several-segment account field, but this plugin doesn't. Making sure it starts with ledgerPrefix, then taking the substring, and then taking the first segment off of the result should be sufficient

2017-08-08 10:11 UTC, sharafian requested changes

2017-08-08 10:11 UTC, sharafian commented on src/model/ethereum.js
> +  const match = account.substring(ledgerPrefix.length).match(/^(0x[0-9A-F]{40})$/g)
this should not include the $, and the first capture group of the match (instead of `match[0]`, which is the entire match) should be returned. That way the plugin works with subledger segments in the address

2017-08-17 13:37 UTC, michielbdejong commented on src/model/ethereum.js
> +  const match = account.substring(ledgerPrefix.length).match(/^(0x[0-9A-F]{40})$/g)
I don't understand, shouldn't subledger segments go in the `ledgerPrefix` part? The way I see it, this plugin lets you map ethereum addresses as accounts on any ledgerPrefix you want, same as https://github.com/ripple/ilp-plugin-xrp-escrow/pull/9

2017-09-19 14:01 UTC, michielbdejong commented on src/model/ethereum.js
> +  const match = account.substring(ledgerPrefix.length).match(/^(0x[0-9A-F]{40})$/g)
bump

2017-09-19 17:51 UTC, sharafian commented on src/model/ethereum.js
> +  const match = account.substring(ledgerPrefix.length).match(/^(0x[0-9A-F]{40})$/g)
subledger would go after the account segment. You can replace the `$` with `($|\.)` though, and it would work.

2017-10-03 17:50 UTC, sharafian approved these changes

2017-10-04 09:53 UTC, merged